version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth-app/Dockerfile
    container_name: auth-app
    depends_on:
      - rabbitmq
      - db
    environment:
      - PORT=${PORT}
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev auth-app

  app:
    build:
      context: ./
      dockerfile: ./apps/nestproject/Dockerfile
    container_name: nestproject-app
    depends_on:
      - rabbitmq
      - db
    environment:
      - PORT=${PORT}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev nestproject

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
